[package]
name = "axon_parser"
version = "0.1.0"
authors = ["A Mackay <amk@gegroup.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
nom = "6.0.0-alpha1"