[package]
name = "axon_parser"
version = "0.1.0"
authors = ["A Mackay <opensauceburner@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axon_parseast_parser = "0.1"
raystack = "0.6"